apiVersion: apps/v1
kind: Deployment
metadata:
  name: faust-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faust-consumer
  template:
    metadata:
      labels:
        app: faust-consumer
    spec:
      containers:
        - name: faust
          image: silasschroeder/stream-processing:0.9
          imagePullPolicy: Always
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: faust-consumer
spec:
  scaleTargetRef:
    name: faust-consumer # DEPLOYMENT
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 5 # Sekunden
  cooldownPeriod: 60
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: my-kafka-cluster-kafka-bootstrap:9092
        consumerGroup: s3-stream # Faust App-Name = Consumer-Group
        topic: tracking-data
        lagThreshold: "1000" # Skaliert, wenn Lag > 1000
        offsetResetPolicy: latest
