apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tracking-data
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  partitions: 5
  replicas: 1
  config:
    retention.ms: 62400
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: model-results
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  partitions: 5
  replicas: 1
  config:
    retention.ms: 62400
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-dual-role-pool
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      default.replication.factor: 3
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
