# DEPLOYMENT FOR PODS RUNNING THE FRONT END APPLICATION
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfisterer-front-end
  labels:
    app: pfisterer-front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pfisterer-front-end
  template:
    metadata:
      labels:
        app: pfisterer-front-end
    spec:
      containers:
        - name: pfisterer-front-end-container
          image: silasschroeder/pfisterer-front-end:0.4.4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
# SERVICE TO EXPOSE THE FRONT END APPLICATION INTERNALLY IN THE CLUSTER
kind: Service
apiVersion: v1
metadata:
  name: pfisterer-front-end-service
spec:
  selector:
    app: pfisterer-front-end
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
# INGRESS TO EXPOSE THE FRONT END APPLICATION TO THE OUTSIDE WORLD
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pfisterer-front-end-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pfisterer-front-end-service
                port:
                  number: 3000
